var React = require('react');

module.exports = React.createClass({
  render: function() {
    return (
      <div>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
      <p>Global chat system</p>
    </div>
    );
  }
});